import 'package:intl/intl.dart';

class Teacher {
  int? id;
  String? docId;
  String name;
  String mobile;
  DateTime? startingDate;
  String status;
  String leavingDate;
  int salary;
  bool isSaved;

  Teacher({
    this.id,
    this.docId,
    required this.name,
    this.mobile = '',
    this.startingDate,
    this.status = '',
    this.leavingDate = '',
    this.salary = 0,
    this.isSaved = false,
  });

  Map<String, dynamic> toMap() {
    return {
      // Don't include 'id' when inserting (auto-generated by Supabase)
      // Don't include 'docId' (Firebase-only field, not in Supabase)
      'name': name,
      'mobile_no': mobile.isNotEmpty ? int.tryParse(mobile) : null,
      'starting_date': startingDate != null ? DateFormat('yyyy-MM-dd').format(startingDate!) : null,
      'status': status.isNotEmpty ? status : 'Active',
      'leaving_date': leavingDate.isNotEmpty ? leavingDate : null,
      'salary': salary,
    };
  }
  
  Map<String, dynamic> toMapWithId() {
    return {
      'id': id,
      'name': name,
      'mobile_no': mobile.isNotEmpty ? int.tryParse(mobile) : null,
      'starting_date': startingDate != null ? DateFormat('yyyy-MM-dd').format(startingDate!) : null,
      'status': status.isNotEmpty ? status : 'Active',
      'leaving_date': leavingDate.isNotEmpty ? leavingDate : null,
      'salary': salary,
    };
  }

  factory Teacher.fromMap(Map<String, dynamic> map) {
    DateTime? parseStartingDate;
    // Support both Firebase (startingDate) and Supabase (starting_date) field names
    final startingDateField = map['starting_date'] ?? map['startingDate'];
    if (startingDateField != null) {
      // Handle DateTime object (from PostgreSQL)
      if (startingDateField is DateTime) {
        parseStartingDate = startingDateField;
      } else if (startingDateField.toString().isNotEmpty) {
        // Handle String
        try {
          parseStartingDate = DateTime.tryParse(startingDateField.toString());
        } catch (e) {
          parseStartingDate = null;
        }
      }
    }
    
    int salaryValue = 0;
    if (map['salary'] != null) {
      if (map['salary'] is int) {
        salaryValue = map['salary'];
      } else if (map['salary'] is String) {
        salaryValue = int.tryParse(map['salary']) ?? 0;
      }
    }
    
    // Parse id which may come as int or string (Firestore doc IDs are strings)
    int? idValue;
    if (map['id'] != null) {
      if (map['id'] is int) {
        idValue = map['id'] as int;
      } else if (map['id'] is String) {
        idValue = int.tryParse(map['id'] as String);
      }
    }
    // docId holds the Firestore document ID (string)
    String? docIdValue;
    if (map['docId'] != null) {
      docIdValue = map['docId'].toString();
    }
     
    // Parse mobile_no (NUMERIC in Supabase)
    String mobileValue = '';
    if (map['mobile_no'] != null) {
      mobileValue = map['mobile_no'].toString();
    } else if (map['mobile'] != null) {
      mobileValue = map['mobile'].toString();
    }
    
    return Teacher(
      id: idValue,
      docId: docIdValue,
      name: map['name'] ?? '',
      mobile: mobileValue,
      startingDate: parseStartingDate,
      status: map['status'] ?? '',
      leavingDate: map['leaving_date'] ?? map['leavingDate'] ?? '',
      salary: salaryValue,
      isSaved: true,
    );
  }
}